---
title: "WeeklyUpdate"
author: "Megan Willis-Jackson"
date: "2022-08-08"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(readxl)
library(lubridate)
library(ggplot2)
library(extrafont)
library(plyr)
loadfonts(device = "win")
options(scipen = 999)

```


```{r}
gated_line <- read.csv("C:/Users/Willis-JacksonM/Box/Ongoing Activities/Ridership/COVID-specific Work/downloadable data for public/CSVs for public download/2022.08.02 MBTA Gated Station Validations by line 2018-22.csv") %>%
  mutate(servicedate = mdy(servicedate))

gated_baselines <- read_excel("C:/Users/Willis-JacksonM/Box/Ongoing Activities/Ridership/COVID-specific Work/Weekly Updates/Daily One-Page Update 2022.08.03.xlsx", sheet = "Baselines") %>%
  filter(month == month(max(gated_line$servicedate)))


```


```{r}
wk_end <- Sys.Date() - wday(Sys.Date() + 1) - 7 # for current data remove this minus 7
wk_start <- Sys.Date() - wday(Sys.Date() + 5) - 7  # for current data remove this minus 7

baselines <- gated_baselines %>%
  pivot_wider(names_from = "route_or_line",
              id_cols = "month",
              values_from = "avg_validations") %>%
  mutate(`Total Gated Stations` = `Blue Line` + `Green Line` + `Red Line` + `Orange Line` + `Silver Line`,
         month = "baseline")


current_week <- gated_line %>%
  pivot_wider(names_from = "route_or_line", 
              id_cols = "servicedate", values_from = "validations") %>%
  mutate(`Total Gated Stations` = `Blue Line` + `Green Line` + `Red Line` + `Orange Line` + `Silver Line`) %>%
  filter(servicedate <= wk_end & servicedate >= wk_start) %>%
  summarise(`Blue Line` = mean(`Blue Line`),
            `Green Line` = mean(`Green Line`),
            `Orange Line` = mean(`Orange Line`),
            `Red Line` = mean(`Red Line`),
            `Silver Line` = mean(`Silver Line`),
            `Total Gated Stations` = mean(`Total Gated Stations`)) %>%
  mutate(month = "current") %>%
  rbind(baselines) %>%
  pivot_longer(cols = c("Blue Line","Green Line","Orange Line","Red Line","Silver Line","Total Gated Stations" ),
               names_to = "Line") %>%
  pivot_wider(names_from = "month",
              id_cols = "Line",
              values_from = "value") %>%
  mutate(pct_decrease = (current-baseline)/baseline)


gated_chart <- gated_line %>%
  pivot_wider(names_from = "route_or_line", 
              id_cols = "servicedate", values_from = "validations") %>%
  mutate(`Total Gated Stations` = `Blue Line` + `Green Line` + `Red Line` + `Orange Line` + `Silver Line`) %>%
  filter(servicedate <= wk_end & servicedate >= (wk_end-60))



```


# Plot

opmi_rl = "#DA291C",
    opmi_ol = "#ED8B00",
    opmi_gl = "#00843D",
    opmi_bl = "#003DA5",
    opmi_bus = "#FFC72C",
    opmi_ferry = "#008EAA",
    opmi_cr = "#80276C",
    opmi_sl = "#7C878E",
    opmi_ride = "#52BBc5",
    opmi_subway = "#4A4F5C"

```{r}
gated_station_chart <- function(data = "gated_chart", servicedate = "servicedate", line, line_color){
  
  ggplot(data) +
  geom_line(aes(x = servicedate,
                y = .data[[line]]), 
            color = ifelse(line_color == "red",
                           "#DA291C",
                    ifelse(line_color == "orange",
                           "#ED8B00",
                    ifelse(line_color == "green",
                           "#00843D",
                    ifelse(line_color == "blue",
                           "#003DA5", "#4A4F5C"))))) +
  geom_point(aes(x = servicedate,
                 y = .data[[line]]), 
            color = ifelse(line_color == "red",
                           "#DA291C",
                    ifelse(line_color == "orange",
                           "#ED8B00",
                    ifelse(line_color == "green",
                           "#00843D",
                    ifelse(line_color == "blue",
                           "#003DA5", "#4A4F5C"))))) +
  scale_x_date(name = NULL,
               date_labels = "%m/%d",
               date_breaks = "1 week",
               limits = c(min(data[[servicedate]]),max(data[[servicedate]]))) +
  scale_y_continuous(name = NULL,
                     breaks = brks <- seq(0, 
                                          round_any(max(data[[line]]),
                                                    accuracy = 100000,
                                                    f = ceiling), 
                                          by = round_any(max(data[[line]]),
                                                    accuracy = 100000,
                                                    f = ceiling)/6),
                     labels = paste(prettyNum(brks, big.mark = ",")),
                     limits = c(0, max(brks))) +
  theme(text = element_text(family = "Calibri"),
        panel.background = element_blank(), 
        panel.grid.major.y = element_line(color = "grey89"),
        panel.grid.major.x = element_blank(),
        axis.ticks.y = element_blank())

 ggsave("totalgated.jpg", height = 3.5, width = 7)
  
}

gated_station_chart(gated_chart, line = "Total Gated Stations", line_color = "black")





```

















